version: "3.5"

services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: emin
      MINIO_ROOT_PASSWORD: eminemin
    command: server --console-address ":9001" /data
